<?php
namespace mpcmf\modules\processHandler\controllers;

use greevex\gss\lib\variableAction;
use mpcmf\apps\processHandler\libraries\processManager\processHandler;
use mpcmf\modules\moduleBase\controllers\controllerBase;
use mpcmf\modules\moduleBase\exceptions\mapperException;
use mpcmf\modules\moduleBase\exceptions\modelException;
use mpcmf\modules\processHandler\mappers\processMapper;
use mpcmf\modules\processHandler\mappers\serverMapper;
use mpcmf\modules\processHandler\models\processModel;
use mpcmf\system\helper\io\codes;
use mpcmf\system\pattern\singleton;
use \mpcmf\system\acl\aclManager;

/**
 * Class processController
 *
 * Process manager
 *
 *
 * @generated by mpcmf/codeManager
 *
 * @package mpcmf\modules\processHandler\controllers;
 * @date 2017-01-20 16:14:08
 *
 * @author Gregory Ostrovsky <greevex@gmail.com>
 * @author Gadel Raymanov <raymanovg@gmail.com>
 */
class processController
    extends controllerBase
{

    use singleton;
}
