<?php
/**
 * @generated by mpcmf/codeManager
 *
 * @package mpcmf\modules\sds\module\mapper\processMapper
 * @date 2017-01-20 16:14:08
 *
 * @author Gadel Raymanov <raymanovg@gmail.com>
 */
\mpcmf\system\configuration\config::setConfig(__FILE__, [
    'storage' => [
        'configSection' => 'default',
        'db' => 'processHandler',
        'collection' => 'processes'
    ]
]);