<?php
namespace mpcmf\modules\processHandler\mappers;


use mpcmf\modules\moduleBase\mappers\mapperBase;
use mpcmf\system\pattern\singleton;

/**
 * Class processMapper
 *
 * Process manager
 *
 *
 * @generated by mpcmf/codeManager
 *
 * @package mpcmf\modules\processHandler\mappers
 * @date 2017-01-20 16:14:08
 *
 * @author Gregory Ostrovsky <greevex@gmail.com>
 * @author Gadel Raymanov <raymanovg@gmail.com>
 */
class serverMapper
    extends mapperBase
{

    use singleton;

    const FIELD___ID = '_id';
    const FIELD__HOST = 'host';
    const FIELD__NAME = 'name';
    const FIELD__LAST_PING = 'last_ping';
    const FIELD__CPU = 'cpu';
    const FIELD__RAM = 'ram';
    const FIELD__LA = 'la';
    const FIELD__CPU_USAGE = 'cpu_usage';
    const FIELD__RAM_USAGE = 'ram_usage';


    public function getPublicName()
    {
        return 'Servers';
    }

    /**
     * Entity map
     *
     * @return array[]
     */
    public function getMap()
    {
        return [
            self::FIELD___ID => [
                'getter' => 'getMongoId',
                'setter' => 'setMongoId',
                'role' => [
                    'key' => true,
                    'generate-key' => true,
                ],
                'name' => 'Mongo ID',
                'description' => 'Mongo ID',
                'type' => 'string',
                'formType' => 'text',
                'validator' => [],
                'relations' => [],
                'options' => [
                    'required' => false,
                    'unique' => true,
                ],
            ],
            self::FIELD__NAME => [
                'getter' => 'getName',
                'setter' => 'setName',
                'role' => [
                ],
                'name' => 'Server name',
                'description' => 'Server name',
                'type' => 'string',
                'formType' => 'text',
                'validator' => [],
                'relations' => [],
                'options' => [
                    'required' => false,
                    'unique' => true,
                ],
            ],
            self::FIELD__HOST => [
                'getter' => 'getHost',
                'setter' => 'setHost',
                'role' => [
                    'title' => true,
                    'searchable' => true,
                    'sortable' => true,],
                'name' => 'Host Name',
                'description' => 'Server\'s address where will be started process',
                'type' => 'string',
                'formType' => 'text',
                'validator' => [],
                'options' => [
                    'required' => true,
                    'unique' => true,
                ],
            ],
            self::FIELD__LAST_PING => [
                'getter' => 'getLastPing',
                'setter' => 'setLastPing',
                'role' => [
                ],
                'name' => 'Last ping',
                'description' => 'Last ping',
                'type' => 'int',
                'formType' => 'datetimepicker',
                'validator' => [],
                'relations' => [],
                'options' => [
                    'required' => false,
                    'unique' => false,
                ],
            ],
            self::FIELD__LA => [
                'getter' => 'getLA',
                'setter' => 'setLA',
                'role' => [
                ],
                'name' => 'Load average',
                'description' => 'LA',
                'type' => 'float',
                'formType' => 'text',
                'validator' => [],
                'relations' => [],
                'options' => [
                    'required' => false,
                    'unique' => false,
                ],
            ],
            self::FIELD__CPU => [
                'getter' => 'getCpu',
                'setter' => 'setCpu',
                'role' => [
                ],
                'name' => 'CPU',
                'description' => 'CPU (cores)',
                'type' => 'int',
                'formType' => 'text',
                'validator' => [],
                'relations' => [],
                'options' => [
                    'required' => false,
                    'unique' => false,
                ],
            ],
            self::FIELD__RAM => [
                'getter' => 'getRam',
                'setter' => 'setRam',
                'role' => [
                ],
                'name' => 'Ram (Mbyte)',
                'description' => 'Ram (Mbyte)',
                'type' => 'int',
                'formType' => 'text',
                'validator' => [],
                'relations' => [],
                'options' => [
                    'required' => false,
                    'unique' => false,
                ],
            ],
            self::FIELD__CPU_USAGE => [
                'getter' => 'getCpuUsage',
                'setter' => 'setCpuUsage',
                'role' => [
                ],
                'name' => 'Cpu Usage',
                'description' => 'Cpu Usage (percent)',
                'type' => 'int',
                'formType' => 'text',
                'validator' => [],
                'relations' => [],
                'options' => [
                    'required' => false,
                    'unique' => false,
                ],
            ],
            self::FIELD__RAM_USAGE => [
                'getter' => 'getRamUsage',
                'setter' => 'setRamUsage',
                'role' => [
                ],
                'name' => 'Ram Usage',
                'description' => 'Ram Usage (percent)',
                'type' => 'int',
                'formType' => 'text',
                'validator' => [],
                'relations' => [],
                'options' => [
                    'required' => false,
                    'unique' => false,
                ],
            ],
        ];
    }
}