<?php
namespace mpcmf\modules\processHandler\models;

use mpcmf\modules\moduleBase\models\modelBase;
use mpcmf\system\pattern\singleton;

/**
 * Class processModel
 *
 * Process manager
 *
 *
 * @generated by mpcmf/codeManager
 *
 * @package mpcmf\modules\processHandler\models
 * @date 2017-01-20 16:14:08
 *
 * @author Dmitry Emelyanov <gilberg.vrn@gmail.com>
 *
 * @method string getMongoId() MongoId
 * @method $this setMongoId(string $value) MongoId
 * @method string getName() Name
 * @method $this setName(string $value) Name
 * @method string getHost() Host
 * @method $this setHost(string $value) Host
 * @method string getLastPing() LastPing
 * @method $this setLastPing(string $value) LastPing
 * @method string getLA() LA
 * @method $this setLA(float $value) LA
 * @method string getCpu() CPU
 * @method $this setCpu(int $value) CPU
 * @method int getRam() RAM
 * @method $this setRam(int $value) RAM
 * @method int getCpuUsage() CPU Usage
 * @method $this setCpuUsage(int $value) CPU Usage
 * @method int getRamUsage() RAM Usage
 * @method $this setRamUsage(int $value) RAM Usage
 *
 */
class serverModel
    extends modelBase
{

    use singleton;
}